version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Scanned at root in its isolated repo
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
